# Getting started

Once you've chosen your scenario, download the data from [the Iowa website](https://data.iowa.gov/Economy/Iowa-Liquor-Sales/m3tr-qhgy) in csv format. Start by loading the data with pandas. You may need to parse the date columns appropriately.

In [1]:
# Loading initial libraries, starting with data.table and lubridate for easy cleaning
library(data.table)
library(lubridate)
library(ggplot2)
# reading in the 10 pct CSV and converting it to a data frame (possibly redundant)
liquor = read.csv('/Users/mikesanders/Desktop/DSI-SF-1-msanders2288/project-03/Iowa_Liquor_sales_sample_10pct.csv')
liquor_data = data.table(liquor)
#Printing out the head
head(liquor_data)

Attaching package: ‘lubridate’

The following objects are masked from ‘package:data.table’:

    hour, mday, month, quarter, wday, week, yday, year

         Date Store.Number         City Zip.Code County.Number     County
1: 11/04/2015         3717       SUMNER    50674             9     Bremer
2: 03/02/2016         2614    DAVENPORT    52807            82      Scott
3: 02/11/2016         2106  CEDAR FALLS    50613             7 Black Hawk
4: 02/03/2016         2501         AMES    50010            85      Story
5: 08/18/2015         3654      BELMOND    50421            99     Wright
6: 04/20/2015         2569 CEDAR RAPIDS    52402            57       Linn
   Category             Category.Name Vendor.Number Item.Number
1:  1051100          APRICOT BRANDIES            55       54436
2:  1011100          BLENDED WHISKIES           395       27605
3:  1011200 STRAIGHT BOURBON WHISKIES            65       19067
4:  1071100        AMERICAN COCKTAILS           395       59154
5:  1031080            VODKA 80 PROOF           297       35918
6:  1041100         AMERICAN DRY GINS           205       31473
            Item.Description Bottle.Volume..ml. State.Bottle.Cost
1: Mr. Boston Apricot Brandy                750             $4.50
2:                   Tin Cup                750            $13.75
3:                  Jim Beam               1000            $12.59
4:   1800 Ultimate Margarita               1750             $9.50
5:        Five O'clock Vodka               1750             $7.20
6:         New Amsterdam Gin               1750            $13.32
   State.Bottle.Retail Bottles.Sold Sale..Dollars. Volume.Sold..Liters.
1:               $6.75           12         $81.00                  9.0
2:              $20.63            2         $41.26                  1.5
3:              $18.89           24        $453.36                 24.0
4:              $14.25            6         $85.50                 10.5
5:              $10.80           12        $129.60                 21.0
6:              $19.98            6        $119.88                 10.5
   Volume.Sold..Gallons.
1:                  2.38
2:                  0.40
3:                  6.34
4:                  2.77
5:                  5.55
6:                  2.77

In [3]:
#Removing the Gallons Sold column because it's redundant. Hard liquor is measured in Liters.
liquor_data$Volume.Sold..Gallons. = NULL

In [4]:
# Getting the list of names from the data frame
names(liquor_data)

 [1] "Date"                 "Store.Number"         "City"
 [4] "Zip.Code"             "County.Number"        "County"
 [7] "Category"             "Category.Name"        "Vendor.Number"
[10] "Item.Number"          "Item.Description"     "Bottle.Volume..ml."
[13] "State.Bottle.Cost"    "State.Bottle.Retail"  "Bottles.Sold"
[16] "Sale..Dollars."       "Volume.Sold..Liters."

In [5]:
#Renaming some of the columns. Leaving the dots as spaces for ease of use later.
names(liquor_data) = c('Date', 'Store.Number', 'City', 'Zip.Code', 'County.Number','County', 'Category','Category.Name', 'Vendor.Number',
                       'Item.Number', 'Item.Description', 'Bottle.Volume(ml)','State.Bottle.Cost',
                       'State.Bottle.Retail', 'Bottles.Sold','Sale.Dollars','Volume.Sold(Liters)')
#Reprint names
names(liquor_data)

 [1] "Date"                "Store.Number"        "City"
 [4] "Zip.Code"            "County.Number"       "County"
 [7] "Category"            "Category.Name"       "Vendor.Number"
[10] "Item.Number"         "Item.Description"    "Bottle.Volume(ml)"
[13] "State.Bottle.Cost"   "State.Bottle.Retail" "Bottles.Sold"
[16] "Sale.Dollars"        "Volume.Sold(Liters)"

In [6]:
#printing out the structure of the data frame
str(liquor_data)

Classes ‘data.table’ and 'data.frame':	270955 obs. of  17 variables:
 $ Date               : Factor w/ 274 levels "01/04/2016","01/05/2015",..: 237 69 48 38 189 116 181 157 1 240 ...
 $ Store.Number       : int  3717 2614 2106 2501 3654 2569 2596 3456 4757 4346 ...
 $ City               : Factor w/ 385 levels "ACKLEY","ADAIR",..: 337 82 52 12 31 53 272 63 36 313 ...
 $ Zip.Code           : Factor w/ 415 levels "50002","50003",..: 179 413 154 5 104 361 366 107 14 344 ...
 $ County.Number      : num  9 82 7 85 99 57 90 17 77 6 ...
 $ County             : Factor w/ 100 levels "","Adair","Adams",..: 10 83 8 86 100 58 91 18 78 7 ...
 $ Category           : num  1051100 1011100 1011200 1071100 1031080 ...
 $ Category.Name      : Factor w/ 72 levels "","100 PROOF VODKA",..: 12 15 60 6 67 7 8 18 37 20 ...
 $ Vendor.Number      : int  55 395 65 395 297 205 85 65 370 65 ...
 $ Item.Number        : int  54436 27605 19067 59154 35918 31473 52806 10628 34006 82610 ...
 $ Item.Description   : Factor w/ 2173 levels "10 Cane Rum",..: 1383 2019 1097 10 823 1398 1217 388 64 647 ...
 $ Bottle.Volume(ml)  : int  750 750 1000 1750 1750 1750 750 1750 750 1000 ...
 $ State.Bottle.Cost  : Factor w/ 1086 levels "$0.89","$0.97",..: 718 198 154 1054 928 184 882 275 107 949 ...
 $ State.Bottle.Retail: Factor w/ 1112 levels "$1.34","$1.46",..: 940 412 350 184 48 382 1106 492 300 79 ...
 $ Bottles.Sold       : int  12 2 24 6 12 6 3 2 4 2 ...
 $ Sale.Dollars       : Factor w/ 6580 levels "$1.34","$1.46",..: 5972 3987 4274 6114 767 537 2990 4344 5476 2266 ...
 $ Volume.Sold(Liters): num  9 1.5 24 10.5 21 10.5 2.25 3.5 3 2 ...
 - attr(*, ".internal.selfref")=<externalptr>

In [7]:
#Converting Date column to Date Time using lubridate
liquor_data$Date = mdy(liquor_data$Date)

In [8]:
head(liquor_data)

         Date Store.Number         City Zip.Code County.Number     County
1: 2015-11-04         3717       SUMNER    50674             9     Bremer
2: 2016-03-02         2614    DAVENPORT    52807            82      Scott
3: 2016-02-11         2106  CEDAR FALLS    50613             7 Black Hawk
4: 2016-02-03         2501         AMES    50010            85      Story
5: 2015-08-18         3654      BELMOND    50421            99     Wright
6: 2015-04-20         2569 CEDAR RAPIDS    52402            57       Linn
   Category             Category.Name Vendor.Number Item.Number
1:  1051100          APRICOT BRANDIES            55       54436
2:  1011100          BLENDED WHISKIES           395       27605
3:  1011200 STRAIGHT BOURBON WHISKIES            65       19067
4:  1071100        AMERICAN COCKTAILS           395       59154
5:  1031080            VODKA 80 PROOF           297       35918
6:  1041100         AMERICAN DRY GINS           205       31473
            Item.Description Bottle.Volume(ml) State.Bottle.Cost
1: Mr. Boston Apricot Brandy               750             $4.50
2:                   Tin Cup               750            $13.75
3:                  Jim Beam              1000            $12.59
4:   1800 Ultimate Margarita              1750             $9.50
5:        Five O'clock Vodka              1750             $7.20
6:         New Amsterdam Gin              1750            $13.32
   State.Bottle.Retail Bottles.Sold Sale.Dollars Volume.Sold(Liters)
1:               $6.75           12       $81.00                 9.0
2:              $20.63            2       $41.26                 1.5
3:              $18.89           24      $453.36                24.0
4:              $14.25            6       $85.50                10.5
5:              $10.80           12      $129.60                21.0
6:              $19.98            6      $119.88                10.5

In [9]:
#Removing '$' from the money columns and changing them to numerics

liquor_data$State.Bottle.Cost = as.numeric(sub('\\$','',as.character(liquor_data$State.Bottle.Cost)))
liquor_data$Sale.Dollars = as.numeric(sub('\\$','',as.character(liquor_data$Sale.Dollars)))
liquor_data$State.Bottle.Retail = as.numeric(sub('\\$','',as.character(liquor_data$State.Bottle.Retail)))

#rechecking the structure of the data frame
summary(liquor_data)

      Date                      Store.Number              City
 Min.   :2015-01-05 00:00:00   Min.   :2106   DES MOINES    : 23724
 1st Qu.:2015-05-04 00:00:00   1st Qu.:2604   CEDAR RAPIDS  : 18888
 Median :2015-08-19 00:00:00   Median :3722   DAVENPORT     : 11580
 Mean   :2015-08-20 00:22:11   Mean   :3590   WATERLOO      :  8425
 3rd Qu.:2015-12-10 00:00:00   3rd Qu.:4378   COUNCIL BLUFFS:  8060
 Max.   :2016-03-31 00:00:00   Max.   :9023   SIOUX CITY    :  7992
                                              (Other)       :192286
    Zip.Code      County.Number             County          Category
 50010  :  7091   Min.   : 1.00   Polk         : 49102   Min.   :1011100
 52402  :  7047   1st Qu.:31.00   Linn         : 23511   1st Qu.:1012200
 52240  :  6138   Median :62.00   Scott        : 16678   Median :1031200
 50613  :  5281   Mean   :57.23   Black Hawk   : 15083   Mean   :1043888
 52001  :  4768   3rd Qu.:77.00   Johnson      : 13189   3rd Qu.:1062310
 51501  :  4665   Max.   :99.00   Pottawattamie:  9111   Max.   :1701100
 (Other):235965   NA's   :1077    (Other)      :144281   NA's   :68
                   Category.Name    Vendor.Number    Item.Number
 VODKA 80 PROOF           : 35373   Min.   : 10.0   Min.   :   168
 CANADIAN WHISKIES        : 27087   1st Qu.:115.0   1st Qu.: 26827
 STRAIGHT BOURBON WHISKIES: 15342   Median :260.0   Median : 38176
 SPICED RUM               : 14631   Mean   :256.4   Mean   : 45975
 VODKA FLAVORED           : 14001   3rd Qu.:380.0   3rd Qu.: 64573
 TEQUILA                  : 12109   Max.   :978.0   Max.   :995507
 (Other)                  :152412
                    Item.Description  Bottle.Volume(ml) State.Bottle.Cost
 Black Velvet               :  7233   Min.   :  50.0    Min.   :  0.890
 Hawkeye Vodka              :  6689   1st Qu.: 750.0    1st Qu.:  5.500
 Five O'clock Vodka         :  4512   Median : 750.0    Median :  8.000
 Smirnoff Vodka 80 Prf      :  3435   Mean   : 924.8    Mean   :  9.773
 Captain Morgan Spiced Rum  :  3356   3rd Qu.:1000.0    3rd Qu.: 11.920
 Seagrams 7 Crown Bl Whiskey:  3280   Max.   :6000.0    Max.   :425.000
 (Other)                    :242450
 State.Bottle.Retail  Bottles.Sold       Sale.Dollars      Volume.Sold(Liters)
 Min.   :  1.34      Min.   :   1.000   Min.   :    1.34   Min.   :   0.100
 1st Qu.:  8.27      1st Qu.:   2.000   1st Qu.:   30.45   1st Qu.:   1.500
 Median : 12.27      Median :   6.000   Median :   70.56   Median :   5.250
 Mean   : 14.68      Mean   :   9.871   Mean   :  128.90   Mean   :   8.981
 3rd Qu.: 17.88      3rd Qu.:  12.000   3rd Qu.:  135.00   3rd Qu.:  10.500
 Max.   :637.50      Max.   :2508.000   Max.   :36392.40   Max.   :2508.000

In [11]:
#creating a new data frame with sales by date (Maybe not useful for this project, but still fun)

# datesales = liquor_data[,.(Sale.Dollars.Sum = sum(Sale.Dollars)),by=Date]
# datesales

countysales = liquor_data[,.(Sale.Dollars.Mean = mean(Sale.Dollars)),by=County]
countysales
countynames = c(countysales$county)

            County Sale.Dollars.Mean
  1:        Bremer          91.41308
  2:         Scott         148.02274
  3:    Black Hawk         128.40892
  4:         Story         120.02154
  5:        Wright         119.35247
  6:          Linn         133.99809
  7:       Wapello          93.61467
  8:   Cerro Gordo         109.20908
  9:          Polk         158.55479
 10:        Benton          81.78101
 11:       Mahaska         103.56830
 12:           Lee         146.22081
 13:       Johnson         158.56440
 14:        Jasper          72.86343
 15:          Tama          79.25953
 16:         Sioux         147.84375
 17:     Dickinson         132.86764
 18: Pottawattamie         140.56581
 19:        Warren         125.06603
 20:       Webster         141.03535
 21:         Boone         105.85525
 22:       Jackson          98.01262
 23:       Carroll         160.48846
 24:      Hamilton          91.76761
 25:      Woodbury         146.36299
 26:    Washington         112.49487
 27:         Floyd         149.25326
 28:      Delaware         144.42177
 29:       O'Brien          96.26495
 30:   Buena Vista          78.07838
 31:        Grundy          68.83094
 32:       Dubuque         139.55858
 33:         Adair          95.01084
 34:      Crawford         138.46321
 35:         Henry         132.13075
 36:       Guthrie          86.45363
 37:    Winneshiek         113.85858
 38:          Clay          92.46209
 39:     Muscatine          89.92326
 40:        Taylor          50.27211
 41:      Harrison          56.30422
 42:        Hardin         133.62156
 43:       Kossuth         129.08309
 44:        Dallas         231.18360
 45:       Decatur          88.41643
 46:       Clinton         117.74103
 47:        Butler          84.82495
 48:    Des Moines         114.45123
 49:       Calhoun          84.88804
 50:       Fayette         135.64051
 51:         Jones          64.77757
 52:                       108.48067
 53:       Hancock         101.96926
 54:          Iowa         106.94104
 55:        Howard         152.32339
 56:     Appanoose          94.46516
 57:     Jefferson         129.14120
 58:         Emmet          86.24459
 59:      Marshall         117.01761
 60:          Page         109.95327
 61:         Cedar          68.69775
 62:       Clayton          71.18315
 63:           Sac          71.61435
 64:        Monona          54.00759
 65:     Allamakee          94.76054
 66:     Winnebago         100.27230
 67:     Poweshiek          79.50751
 68:        Marion          92.83848
 69:      Buchanan         103.69757
 70:      Franklin          81.91884
 71:      Cherokee          99.42351
 72:      Humboldt         104.46981
 73:        Greene         110.66951
 74:        Keokuk          53.33890
 75:      Plymouth         109.40461
 76:        Shelby         153.51973
 77:        Clarke         112.72833
 78:     Palo Alto          66.07965
 79:          Cass         109.37340
 80:          Lyon          81.39500
 81:    Pocahontas          85.32063
 82:           Ida         120.17994
 83:         Union         108.18691
 84:       Fremont         119.64630
 85:    Montgomery          96.55142
 86:        Louisa          63.43514
 87:      Mitchell          50.94441
 88:         Mills         109.09441
 89:       Madison         108.80718
 90:         Davis          65.01241
 91:         Lucas         101.22099
 92:       Audubon          86.58828
 93:         Wayne          80.83513
 94:       Osceola          86.24327
 95:     Chickasaw          95.81306
 96:     Van Buren          88.02437
 97:         Worth          97.00848
 98:        Monroe          96.03683
 99:         Adams          53.16970
100:      Ringgold          90.49886
            County Sale.Dollars.Mean

# Explore the data

Perform some exploratory statistical analysis and make some plots, such as histograms of transaction totals, bottles sold, etc.

In [12]:
# max(liquor_data$Sale.Dollars)

In [13]:
# geom_histogram(liquor_data$Sale.Dollars)

In [14]:
# fit = lm('Sale.Dollars.Mean ~ County', data= countysales)
# summary(fit)
# model(fit)

In [15]:
#plot(fit)

In [16]:
# library(ggplot2)
# geom_bar(data=countysales, stat='identity')

In [17]:
# Attempting a regression plot
# head(liquor_data)

In [18]:
liquor_num_cols = sapply(liquor_data, is.numeric)
liquor_num = liquor_data[, liquor_num_cols, with=F]

In [19]:
head(liquor_num)

   Store.Number County.Number Category Vendor.Number Item.Number
1:         3717             9  1051100            55       54436
2:         2614            82  1011100           395       27605
3:         2106             7  1011200            65       19067
4:         2501            85  1071100           395       59154
5:         3654            99  1031080           297       35918
6:         2569            57  1041100           205       31473
   Bottle.Volume(ml) State.Bottle.Cost State.Bottle.Retail Bottles.Sold
1:               750              4.50                6.75           12
2:               750             13.75               20.63            2
3:              1000             12.59               18.89           24
4:              1750              9.50               14.25            6
5:              1750              7.20               10.80           12
6:              1750             13.32               19.98            6
   Sale.Dollars Volume.Sold(Liters)
1:        81.00                 9.0
2:        41.26                 1.5
3:       453.36                24.0
4:        85.50                10.5
5:       129.60                21.0
6:       119.88                10.5

In [20]:
cor(liquor_num, use='pairwise.complete.obs')

                    Store.Number County.Number      Category Vendor.Number
Store.Number         1.000000000   0.007509702 -0.0121108827  -0.004532983
County.Number        0.007509702   1.000000000 -0.0063355652   0.001745501
Category            -0.012110883  -0.006335565  1.0000000000   0.091920299
Vendor.Number       -0.004532983   0.001745501  0.0919202989   1.000000000
Item.Number         -0.026386273   0.006810367  0.1163851228   0.136119966
Bottle.Volume(ml)   -0.063475419  -0.027694130 -0.0092936987   0.024561220
State.Bottle.Cost   -0.071381974   0.012186154 -0.0133578036   0.003477176
State.Bottle.Retail -0.071520216   0.012112654 -0.0135446238   0.003085274
Bottles.Sold         0.014421859   0.018945200 -0.0002079772  -0.002115853
Sale.Dollars        -0.017940891   0.019851364  0.0063823743  -0.012277057
Volume.Sold(Liters) -0.017696195   0.010199013 -0.0043754599  -0.007431824
                     Item.Number Bottle.Volume(ml) State.Bottle.Cost
Store.Number        -0.026386273      -0.063475419      -0.071381974
County.Number        0.006810367      -0.027694130       0.012186154
Category             0.116385123      -0.009293699      -0.013357804
Vendor.Number        0.136119966       0.024561220       0.003477176
Item.Number          1.000000000      -0.057282177       0.097878937
Bottle.Volume(ml)   -0.057282177       1.000000000       0.312841408
State.Bottle.Cost    0.097878937       0.312841408       1.000000000
State.Bottle.Retail  0.097612133       0.313818691       0.999960188
Bottles.Sold        -0.004765623      -0.012476095      -0.062979537
Sale.Dollars         0.002987019       0.082445576       0.135930690
Volume.Sold(Liters) -0.009555464       0.156257967       0.009295522
                    State.Bottle.Retail  Bottles.Sold Sale.Dollars
Store.Number               -0.071520216  0.0144218591 -0.017940891
County.Number               0.012112654  0.0189452000  0.019851364
Category                   -0.013544624 -0.0002079772  0.006382374
Vendor.Number               0.003085274 -0.0021158533 -0.012277057
Item.Number                 0.097612133 -0.0047656232  0.002987019
Bottle.Volume(ml)           0.313818691 -0.0124760950  0.082445576
State.Bottle.Cost           0.999960188 -0.0629795372  0.135930690
State.Bottle.Retail         1.000000000 -0.0628307420  0.136114234
Bottles.Sold               -0.062830742  1.0000000000  0.825445795
Sale.Dollars                0.136114234  0.8254457951  1.000000000
Volume.Sold(Liters)         0.009736495  0.8833483969  0.846420395
                    Volume.Sold(Liters)
Store.Number               -0.017696195
County.Number               0.010199013
Category                   -0.004375460
Vendor.Number              -0.007431824
Item.Number                -0.009555464
Bottle.Volume(ml)           0.156257967
State.Bottle.Cost           0.009295522
State.Bottle.Retail         0.009736495
Bottles.Sold                0.883348397
Sale.Dollars                0.846420395
Volume.Sold(Liters)         1.000000000

In [21]:
tmp = liquor_num[, retail_per_liter := max(State.Bottle.Retail/(get('Bottle.Volume(ml)')/1000)), by='Vendor.Number']

In [22]:
head(tmp)

   Store.Number County.Number Category Vendor.Number Item.Number
1:         3717             9  1051100            55       54436
2:         2614            82  1011100           395       27605
3:         2106             7  1011200            65       19067
4:         2501            85  1071100           395       59154
5:         3654            99  1031080           297       35918
6:         2569            57  1041100           205       31473
   Bottle.Volume(ml) State.Bottle.Cost State.Bottle.Retail Bottles.Sold
1:               750              4.50                6.75           12
2:               750             13.75               20.63            2
3:              1000             12.59               18.89           24
4:              1750              9.50               14.25            6
5:              1750              7.20               10.80           12
6:              1750             13.32               19.98            6
   Sale.Dollars Volume.Sold(Liters) retail_per_liter
1:        81.00                 9.0            37.00
2:        41.26                 1.5            79.88
3:       453.36                24.0           471.60
4:        85.50                10.5            79.88
5:       129.60                21.0            21.32
6:       119.88                10.5            60.00

In [28]:
liquor_data$multibottle_binary = NULL
head(liquor_data)

         Date Store.Number         City Zip.Code County.Number     County
1: 2015-11-04         3717       SUMNER    50674             9     Bremer
2: 2016-03-02         2614    DAVENPORT    52807            82      Scott
3: 2016-02-11         2106  CEDAR FALLS    50613             7 Black Hawk
4: 2016-02-03         2501         AMES    50010            85      Story
5: 2015-08-18         3654      BELMOND    50421            99     Wright
6: 2015-04-20         2569 CEDAR RAPIDS    52402            57       Linn
   Category             Category.Name Vendor.Number Item.Number
1:  1051100          APRICOT BRANDIES            55       54436
2:  1011100          BLENDED WHISKIES           395       27605
3:  1011200 STRAIGHT BOURBON WHISKIES            65       19067
4:  1071100        AMERICAN COCKTAILS           395       59154
5:  1031080            VODKA 80 PROOF           297       35918
6:  1041100         AMERICAN DRY GINS           205       31473
            Item.Description Bottle.Volume(ml) State.Bottle.Cost
1: Mr. Boston Apricot Brandy               750              4.50
2:                   Tin Cup               750             13.75
3:                  Jim Beam              1000             12.59
4:   1800 Ultimate Margarita              1750              9.50
5:        Five O'clock Vodka              1750              7.20
6:         New Amsterdam Gin              1750             13.32
   State.Bottle.Retail Bottles.Sold Sale.Dollars Volume.Sold(Liters)
1:                6.75           12        81.00                 9.0
2:               20.63            2        41.26                 1.5
3:               18.89           24       453.36                24.0
4:               14.25            6        85.50                10.5
5:               10.80           12       129.60                21.0
6:               19.98            6       119.88                10.5

In [30]:
model = lm('Bottles.Sold ~ Category.Name', data= liquor_data)
summary(model)

Call:
lm(formula = "Bottles.Sold ~ Category.Name", data = liquor_data)

Residuals:
    Min      1Q  Median      3Q     Max
 -15.85   -6.36   -3.30    1.84 2493.37

Coefficients:
                                                  Estimate Std. Error t value
(Intercept)                                     10.1582278  0.9499643  10.693
Category.Name100 PROOF VODKA                     0.0009731  1.0368473   0.001
Category.NameAMARETTO - IMPORTED                 5.8417722 13.8208101   0.423
Category.NameAMERICAN ALCOHOL                   -0.0831842  1.3776011  -0.060
Category.NameAMERICAN AMARETTO                  -2.3565934  1.1515900  -2.046
Category.NameAMERICAN COCKTAILS                 -2.4656315  0.9923425  -2.485
Category.NameAMERICAN DRY GINS                  -0.5378589  0.9946793  -0.541
Category.NameAMERICAN GRAPE BRANDIES             1.0757986  0.9944803   1.082
Category.NameAMERICAN SLOE GINS                 -5.3712456  2.0681411  -2.597
Category.NameANISETTE                           -6.2153707  4.1470203  -1.499
Category.NameAPPLE SCHNAPPS                     -1.9282537  1.2803522  -1.506
Category.NameAPRICOT BRANDIES                   -3.1492107  1.1902574  -2.646
Category.NameBARBADOS RUM                       -5.8401617  1.5341680  -3.807
Category.NameBLACKBERRY BRANDIES                -3.1221519  1.1240129  -2.778
Category.NameBLENDED WHISKIES                   -0.8619604  0.9756151  -0.884
Category.NameBOTTLED IN BOND BOURBON            -6.3950700  1.9759064  -3.237
Category.NameBUTTERSCOTCH SCHNAPPS              -3.8449614  1.2402659  -3.100
Category.NameCANADIAN WHISKIES                   1.8050387  0.9609827   1.878
Category.NameCHERRY BRANDIES                    -4.0339854  1.6219514  -2.487
Category.NameCINNAMON SCHNAPPS                  -5.0704364  1.2979936  -3.906
Category.NameCOFFEE LIQUEURS                    -3.5103700  1.0956340  -3.204
Category.NameCORN WHISKIES                      -7.9082278  6.9592041  -1.136
Category.NameCREAM LIQUEURS                     -3.1319707  0.9965903  -3.143
Category.NameCREME DE ALMOND                    -5.3697663  3.4453524  -1.559
Category.NameDARK CREME DE CACAO                -4.8015400  2.1295897  -2.255
Category.NameDECANTERS & SPECIALTY PACKAGES      3.0376307  1.1809006   2.572
Category.NameDISTILLED SPIRITS SPECIALTY         2.8120620  1.1470483   2.452
Category.NameFLAVORED GINS                      -4.8102278  1.7843151  -2.696
Category.NameFLAVORED RUM                       -2.4662476  0.9903300  -2.490
Category.NameGRAPE SCHNAPPS                      2.5715019  1.6171444   1.590
Category.NameGREEN CREME DE MENTHE              -4.6524363  1.7619608  -2.640
Category.NameHIGH PROOF BEER - AMERICAN         -9.1582278 16.9136328  -0.541
Category.NameIMPORTED AMARETTO                  -2.4154742  1.7230411  -1.402
Category.NameIMPORTED DRY GINS                  -3.3749682  1.0471343  -3.223
Category.NameIMPORTED GRAPE BRANDIES             0.3213994  1.0129374   0.317
Category.NameIMPORTED SCHNAPPS                  -2.3088515  1.0181653  -2.268
Category.NameIMPORTED VODKA                     -0.6269193  0.9776986  -0.641
Category.NameIMPORTED VODKA - MISC              -3.0384922  0.9950353  -3.054
Category.NameIRISH WHISKIES                     -1.0622049  1.0520365  -1.010
Category.NameJAMAICA RUM                        -4.9764097  1.5439647  -3.223
Category.NameJAPANESE WHISKY                    -4.5060539  5.0694868  -0.889
Category.NameLOW PROOF VODKA                    -7.6248945  6.2389826  -1.222
Category.NameMISC. AMERICAN CORDIALS & LIQUEURS -4.4234017  1.0346375  -4.275
Category.NameMISC. IMPORTED CORDIALS & LIQUEURS -2.8153163  0.9964819  -2.825
Category.NameMISCELLANEOUS  BRANDIES            -4.6512834  2.2052452  -2.109
Category.NameMISCELLANEOUS SCHNAPPS             -4.0487237  1.2213203  -3.315
Category.NameOTHER PROOF VODKA                  -4.6966894  2.8660855  -1.639
Category.NamePEACH BRANDIES                     -2.2039506  1.3204686  -1.669
Category.NamePEACH SCHNAPPS                     -1.2030763  1.1171799  -1.077
Category.NamePEPPERMINT SCHNAPPS                -2.7080571  1.0389901  -2.606
Category.NamePUERTO RICO & VIRGIN ISLANDS RUM   -1.0039842  0.9793438  -1.025
Category.NameRASPBERRY SCHNAPPS                 -3.8884910  1.6668956  -2.333
Category.NameROCK & RYE                         -6.4954372  2.7448604  -2.366
Category.NameROOT BEER SCHNAPPS                 -3.3248945  1.6317879  -2.038
Category.NameSCOTCH WHISKIES                    -4.6596232  1.0042616  -4.640
Category.NameSINGLE BARREL BOURBON WHISKIES     -6.4685727  1.6402203  -3.944
Category.NameSINGLE MALT SCOTCH                 -6.2959027  1.0731753  -5.867
Category.NameSPEARMINT SCHNAPPS                 -4.7036824  2.5813587  -1.822
Category.NameSPICED RUM                          2.0284306  0.9702647   2.091
Category.NameSTRAIGHT BOURBON WHISKIES          -2.8917046  0.9693333  -2.983
Category.NameSTRAIGHT RYE WHISKIES              -1.8758071  1.1460095  -1.637
Category.NameSTRAWBERRY SCHNAPPS                -4.7112080  1.6706183  -2.820
Category.NameTENNESSEE WHISKIES                  0.0921605  0.9914519   0.093
Category.NameTEQUILA                            -0.8015510  0.9744395  -0.823
Category.NameTRIPLE SEC                          6.6920958  1.1678484   5.730
Category.NameTROPICAL FRUIT SCHNAPPS            -4.8007810  1.8246639  -2.631
Category.NameVODKA 80 PROOF                      4.4716876  0.9584131   4.666
Category.NameVODKA FLAVORED                     -2.9729554  0.9711681  -3.061
Category.NameWATERMELON SCHNAPPS                -1.3127164  1.4467602  -0.907
Category.NameWHISKEY LIQUEUR                     2.2086773  0.9771116   2.260
Category.NameWHITE CREME DE CACAO               -5.1184269  1.9338899  -2.647
Category.NameWHITE CREME DE MENTHE              -5.8959328  3.2019089  -1.841
                                                Pr(>|t|)
(Intercept)                                      < 2e-16 ***
Category.Name100 PROOF VODKA                    0.999251
Category.NameAMARETTO - IMPORTED                0.672530
Category.NameAMERICAN ALCOHOL                   0.951850
Category.NameAMERICAN AMARETTO                  0.040720 *
Category.NameAMERICAN COCKTAILS                 0.012968 *
Category.NameAMERICAN DRY GINS                  0.588690
Category.NameAMERICAN GRAPE BRANDIES            0.279356
Category.NameAMERICAN SLOE GINS                 0.009401 **
Category.NameANISETTE                           0.133938
Category.NameAPPLE SCHNAPPS                     0.132060
Category.NameAPRICOT BRANDIES                   0.008150 **
Category.NameBARBADOS RUM                       0.000141 ***
Category.NameBLACKBERRY BRANDIES                0.005475 **
Category.NameBLENDED WHISKIES                   0.376964
Category.NameBOTTLED IN BOND BOURBON            0.001210 **
Category.NameBUTTERSCOTCH SCHNAPPS              0.001935 **
Category.NameCANADIAN WHISKIES                  0.060338 .
Category.NameCHERRY BRANDIES                    0.012879 *
Category.NameCINNAMON SCHNAPPS                  9.37e-05 ***
Category.NameCOFFEE LIQUEURS                    0.001356 **
Category.NameCORN WHISKIES                      0.255803
Category.NameCREAM LIQUEURS                     0.001674 **
Category.NameCREME DE ALMOND                    0.119103
Category.NameDARK CREME DE CACAO                0.024154 *
Category.NameDECANTERS & SPECIALTY PACKAGES     0.010103 *
Category.NameDISTILLED SPIRITS SPECIALTY        0.014224 *
Category.NameFLAVORED GINS                      0.007022 **
Category.NameFLAVORED RUM                       0.012763 *
Category.NameGRAPE SCHNAPPS                     0.111802
Category.NameGREEN CREME DE MENTHE              0.008279 **
Category.NameHIGH PROOF BEER - AMERICAN         0.588184
Category.NameIMPORTED AMARETTO                  0.160956
Category.NameIMPORTED DRY GINS                  0.001268 **
Category.NameIMPORTED GRAPE BRANDIES            0.751020
Category.NameIMPORTED SCHNAPPS                  0.023351 *
Category.NameIMPORTED VODKA                     0.521381
Category.NameIMPORTED VODKA - MISC              0.002261 **
Category.NameIRISH WHISKIES                     0.312656
Category.NameJAMAICA RUM                        0.001268 **
Category.NameJAPANESE WHISKY                    0.374080
Category.NameLOW PROOF VODKA                    0.221657
Category.NameMISC. AMERICAN CORDIALS & LIQUEURS 1.91e-05 ***
Category.NameMISC. IMPORTED CORDIALS & LIQUEURS 0.004725 **
Category.NameMISCELLANEOUS  BRANDIES            0.034929 *
Category.NameMISCELLANEOUS SCHNAPPS             0.000916 ***
Category.NameOTHER PROOF VODKA                  0.101274
Category.NamePEACH BRANDIES                     0.095105 .
Category.NamePEACH SCHNAPPS                     0.281532
Category.NamePEPPERMINT SCHNAPPS                0.009150 **
Category.NamePUERTO RICO & VIRGIN ISLANDS RUM   0.305289
Category.NameRASPBERRY SCHNAPPS                 0.019661 *
Category.NameROCK & RYE                         0.017963 *
Category.NameROOT BEER SCHNAPPS                 0.041593 *
Category.NameSCOTCH WHISKIES                    3.49e-06 ***
Category.NameSINGLE BARREL BOURBON WHISKIES     8.02e-05 ***
Category.NameSINGLE MALT SCOTCH                 4.45e-09 ***
Category.NameSPEARMINT SCHNAPPS                 0.068430 .
Category.NameSPICED RUM                         0.036565 *
Category.NameSTRAIGHT BOURBON WHISKIES          0.002853 **
Category.NameSTRAIGHT RYE WHISKIES              0.101670
Category.NameSTRAWBERRY SCHNAPPS                0.004802 **
Category.NameTENNESSEE WHISKIES                 0.925939
Category.NameTEQUILA                            0.410750
Category.NameTRIPLE SEC                         1.00e-08 ***
Category.NameTROPICAL FRUIT SCHNAPPS            0.008513 **
Category.NameVODKA 80 PROOF                     3.08e-06 ***
Category.NameVODKA FLAVORED                     0.002205 **
Category.NameWATERMELON SCHNAPPS                0.364223
Category.NameWHISKEY LIQUEUR                    0.023796 *
Category.NameWHITE CREME DE CACAO               0.008129 **
Category.NameWHITE CREME DE MENTHE              0.065567 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 23.88 on 270883 degrees of freedom
Multiple R-squared:  0.01346,	Adjusted R-squared:  0.0132
F-statistic: 52.04 on 71 and 270883 DF,  p-value: < 2.2e-16